patch -p1 < ../patches/mhash-0.9.9.9-align.patch
patch -p1 < ../patches/mhash-0.9.9.9-force64bit-tiger.patch
patch -p1 < ../patches/mhash-0.9.9.9-fix-snefru-segfault.patch
patch -p1 < ../patches/mhash-0.9.9.9-fix-mem-leak.patch
patch -p1 < ../patches/mhash-0.9.9.9-fix-whirlpool-segfault.patch
patch -p1 < ../patches/mhash-0.9.9.9-autotools-namespace-stomping.patch
patch -p1 < ../patches/mhash-0.9.9.9-maxint.patch
patch -p1 < ../patches/mhash-0.9.9.9-alignment.patch
patch -p1 < ../patches/mhash-0.9.9.9-keygen_test_fix.patch
